Correcting logic to validate Test Lambda step

diff --git a/.github/workflows/aws-lambda-package.yml b/.github/workflows/aws-lambda-package.yml
--- a/.github/workflows/aws-lambda-package.yml
+++ b/.github/workflows/aws-lambda-package.yml
@@ -57,11 +57,11 @@ jobs:
         --layers arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p38-matplotlib:14
     - name: AWS Lambda Test
       run: |
-        result=$(aws lambda invoke --function-name expense-report-generator \
-        --invocation-type Event \
+        error_message=$(aws lambda invoke --function-name expense-report-generator \
+        --invocation-type RequestResponse \
         --payload file://events/test-sqs-event.json \
-        --cli-binary-format raw-in-base64-out /dev/stdout | python -m  json.tool | grep "StatusCode")
-        # Exit if status code from lambda is not 202
-        echo $result
-        if [[ $result == *202* ]]; then echo "Success returned from Lambda"; \
-        else echo "Error returned from Lambda"; exit 1; fi
+        --cli-binary-format raw-in-base64-out /dev/stdout | grep "StatusCode")
+        # Exit if error received from Lambda invocation
+        echo $error_message
+        if [ -z "$error_message" ]; then echo "Error returned from Lambda"; exit 1;\
+        else echo "Success returned from Lambda"; fi
