Correcting Lambda test workflow step

diff --git a/.github/workflows/aws-lambda-package.yml b/.github/workflows/aws-lambda-package.yml
--- a/.github/workflows/aws-lambda-package.yml
+++ b/.github/workflows/aws-lambda-package.yml
@@ -1,4 +1,4 @@
-name: AWS Lambda Package and Deploy
+name: AWS Lambda Package, Deploy and Test
 
 on:
   push:
@@ -42,7 +42,7 @@ jobs:
         aws-region: us-east-2
         role-duration-seconds: 1200
         role-session-name: MySessionName
-    - name: AWS Deploy Lambda
+    - name: AWS Lambda Deploy
       run: |
         aws lambda update-function-code --function-name expense-report-generator \
         --zip-file fileb://expense-report-generator.zip
@@ -50,12 +50,12 @@ jobs:
       uses: jakejarvis/wait-action@master
       with:
         time: '60s'
-    - name: AWS Update Lambda
+    - name: AWS Lambda Update
       run: |
         aws lambda update-function-configuration --function-name expense-report-generator \
         --handler main.lambda_handler \
         --layers arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p38-matplotlib:14
-    - name: Test AWS Lambda
+    - name: AWS Lambda Test
       run: |
         result=$(aws lambda invoke --function-name expense-report-generator \
         --invocation-type Event \
@@ -63,4 +63,5 @@ jobs:
         --cli-binary-format raw-in-base64-out /dev/stdout | python -m  json.tool | grep "StatusCode")
         # Exit if status code from lambda is not 202
         echo $result
-        if [$result != *"202"*]; then exit 1; fi
+        if [[$result != *"202"*]]; then echo "Error returned from Lambda"; exit 1; \
+        else; echo "Success returned from Lambda"; fi
